---
title: "06242025_07092025_tilt"
output: html_document
date: "2025-07-09"
---

### Load libraries
```{r}
library(dplyr)
library(readr)
library(ggplot2)
```

### Load in data
```{r}

upper <- read_csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Tilt/07092025/2403278_Westcott_upper_(0)_Current.csv")
colnames(upper) <- c("datetime", "up_speed", "up_head_deg", "up_vel_N", "up_vel_E")

up_temp <- read_csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Tilt/07092025/2403278_Westcott_upper_(0)_Temperature.csv")
colnames(up_temp) <- c("datetime", "up_temp")

lower <- read_csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Tilt/07092025/2308203_Westcott_lower_(0)_Current.csv")
colnames(lower) <- c("datetime", "low_speed", "low_head_deg", "low_vel_N", "low_vel_E")

low_temp <- read_csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Tilt/07092025/2308203_Westcott_lower_(0)_Temperature.csv")
colnames(low_temp) <- c("datetime", "low_temp")

current <- upper %>%
  left_join(lower, by = "datetime")%>%
  left_join(up_temp, by = "datetime")%>%
  left_join(low_temp, by = "datetime")
  

```

### Tidal current speeds
```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_speed), color = "tomato")+
  geom_point(aes(y = low_speed), color="steelblue")+
  theme_classic()

```


### Temperature data
```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_temp), color = "tomato")+
  geom_point(aes(y = low_temp), color="steelblue")+
  theme_classic()

```

```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_speed), color = "tomato")+
  geom_point(aes(y = low_speed), color="steelblue")+
  theme_classic()+
  scale_x_datetime(limits = as.POSIXct(c("2025-07-04 00:00:00", "2025-07-04 12:00:00")))
```

```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_temp), color = "tomato")+
  geom_point(aes(y = low_temp), color="steelblue")+
  theme_classic()+
  scale_x_datetime(limits = as.POSIXct(c("2025-07-03 00:00:00", "2025-07-04 12:00:00")))
```

