---
title: "0622025_07092025_con"
output: html_document
date: "2025-07-09"
---
### Load Libraries
```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(readxl)

"https://towardsdatascience.com/how-to-automatically-import-and-combine-multiple-files-in-r-30a77c0a7732/"
```


### Load files
```{r}
files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08062025_08192025/con_xlsx_files")


con <- data.frame()

for (file in files){
  name <- gsub(".xlsx","", file)
  con_file <- readxl::read_excel(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08062025_08192025/con_xlsx_files/",file,sep=""))
  con_file$sensor <- name
  con <- rbind(con, con_file)
}

colnames(con) <- c("datetime", "high_range", "temp", "spec_cond", "sal_ppt", "sensor")

con0829<- readxl::read_excel("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08292025_conreadings/STF_CON_15_08292025.xlsx")
colnames(con0829) <- c("datetime", "high_range", "temp", "spec_cond", "sal_ppt")
con0829$datetime <- as.POSIXct(con0829$datetime)

```


```{r}

ggplot(con0829, aes(x=datetime, y=sal_ppt))+
  geom_line()+
  theme_classic()

```
```{r}
#con_current <- left_join(con, current, by = "datetime")

#con_current$Immersed <- ifelse(con_current$up_speed < 10, "Y", "N" )

con_wide <- pivot_wider(con, names_from = sensor, values_from = c(high_range, spec_cond, temp, sal_ppt))

con_wide$Immersed <- ifelse(con_wide$sal_ppt_STF_CON_2_08062025 < 10, "N", "Y" )

con_wide %>%
  filter(Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=sal_ppt, colour = sensor))+
  geom_point()+
  theme_classic()

```

```{r}


con_current %>%
  filter(Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=mean_con, colour = sensor))+
  geom_point()+
  theme_classic()
```


```{r}
hist(con_current$sal_ppt)


clean_con <- con %>%
  filter(datetime < as.POSIXct("2025-08-19 04:35:00") & datetime > as.POSIXct("2025-08-06 03:20:00")) 
  

mean(clean_con$sal_ppt)
sd(clean_con$sal_ppt)

mean(clean_con$spec_cond)
sd(clean_con$spec_cond)

```


```{r}
clean_con <- con %>% 
  filter(!(sensor == "STF_CON_2_08062025"))


mean(clean_con$sal_ppt)
mean(clean_con$spec_cond)
```


```{r}
con2 <- con %>% 
  filter(sensor == "STF_CON_2_08062025")
```

```{r}
con0829 <- con0829[1:2862,]

mean(con0829$sal_ppt)
mean(con0829$spec_cond)
sd(con0829$sal_ppt)
```


