---
title: "DO_comb"
output: html_document
date: "2025-07-14"
---

### Load Libraries

```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(readxl)
library(lubridate)
library(hms)
install.packages("ggpattern")
library(ggpattern)

"https://towardsdatascience.com/how-to-automatically-import-and-combine-multiple-files-in-r-30a77c0a7732/"
```

### Load files

```{r}
files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/07092025/do_xlsx_files")


do1 <- data.frame()

for (file in files){
  name <- gsub(".xlsx","", file)
  do_file <- readxl::read_excel(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/07092025/do_xlsx_files/",file,sep=""))
  do_file$sensor <- name
  do1 <- rbind(do1, do_file)
}

colnames(do1) <- c("datetime", "DO", "temp", "DO_adj", "sensor")

files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/07092025_07222025/do_xlsx_files")


do2 <- data.frame()

for (file in files){
  name <- gsub(".xlsx","", file)
  do_file <- readxl::read_excel(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/07092025_07222025/do_xlsx_files/",file,sep=""))
  do_file$sensor <- name
  do2 <- rbind(do2, do_file)
}

colnames(do2) <- c("datetime", "DO", "temp", "DO_adj", "sensor")



files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/07222025_08062025/do_xlsx_files")


do3 <- data.frame()

for (file in files){
  name <- gsub(".xlsx","", file)
  do_file <- readxl::read_excel(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/07222025_08062025/do_xlsx_files/",file,sep=""))
  do_file$sensor <- name
  do3 <- rbind(do3, do_file)
}

colnames(do3) <- c("datetime", "DO", "temp", "DO_adj", "sensor")

files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08062025_08192025/do_xlsx_files")

do4 <- data.frame()

for (file in files){
  name <- gsub(".xlsx","", file)
  do_file <- readxl::read_excel(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08062025_08192025/do_xlsx_files/",file,sep=""))
  do_file$sensor <- name
  do4 <- rbind(do4, do_file)
}

colnames(do4) <- c("datetime", "DO", "temp", "DO_adj", "sensor")


files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08192025_09152025/do_xlsx_files")

do5 <- data.frame()

for (file in files){
  name <- gsub(".xlsx","", file)
  do_file <- readxl::read_excel(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/08192025_09152025/do_xlsx_files/",file,sep=""))
  do_file$sensor <- name
  do5 <- rbind(do5, do_file)
}

colnames(do5) <- c("datetime", "DO", "temp", "DO_adj", "sensor")

do <- bind_rows(do1, do2, do3, do4, do5)

```

```{r}
do$do_sensor <- substr(do$sensor, start = 8, stop = 9)
do$do_sensor <- gsub('_','',do$do_sensor)
do_sensor_key <- read_excel("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/do_sensor_key.xlsx")

do_sensor_key$do_sensor <- as.character(do_sensor_key$do_sensor)
do <- left_join(do, do_sensor_key, by = "do_sensor")

do <- do[do$datetime < as.POSIXct("2025-08-29 10:25:00"), ]

```

```{r}
do_current <- left_join(do, current, by = "datetime")
do_current$up_Immersed <- ifelse(do_current$up_speed < 10,  "Y", "N" )
do_current$low_Immersed <- ifelse(do_current$low_speed < 10,  "Y", "N" )

do_current %>%
  filter(up_Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=DO_adj, colour = do_sensor))+
  geom_point()+
  theme_classic()

do_current %>%
  filter(low_Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=DO_adj, colour = do_sensor))+
  geom_point()+
  theme_classic()


do_current %>%
  filter(up_Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=temp, colour = do_sensor))+
  geom_point()+
  theme_classic()

do_current %>%
  filter(up_Immersed == "Y",
         tide == "L")%>%
  ggplot(aes(x=temp, y=DO_adj, colour = as.factor(month(datetime))))+
  geom_point()+
  geom_path()+
  facet_wrap(~ do_sensor+tide)+
  theme_classic()

do_current %>%
  filter(up_Immersed == "Y")%>%
  slice_max(temp, n = 1)


```

```{r}
do_current %>%
  filter(bag == c(93:100))%>%
  filter(up_Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=DO_adj, colour = density))+
  geom_point()+
  theme_classic()
```

```{r}
do_current %>%
  filter(bag == c(43:46, 27:30))%>%
  filter(low_Immersed == "Y") %>%
  ggplot(aes(x=datetime, y=DO_adj, colour = density))+
  geom_point()+
  theme_classic()
```

```{r}

do_mean_up <- do_current %>%
  filter(up_Immersed == "Y") %>%
  group_by(datetime, density, tide) %>%
  summarize(mean_DO_up = mean(DO_adj))

do_mean_low <- do_current %>%
  filter(low_Immersed == "Y") %>%
  group_by(datetime, density, tide) %>%
  summarize(mean_DO_low = mean(DO_adj))

do_mean<- do_current %>%
  group_by(datetime, density, tide) %>%
  summarize(mean_DO= mean(DO_adj))


do_mean <- do_current %>%
  group_by(datetime, density, tide) %>%  # whatever defines a single timepoint
  summarise(
    mean_DO = mean(DO_adj, na.rm = TRUE),
    low_Immersed = first(low_Immersed),
    up_Immersed = first(up_Immersed),
    .groups = "drop"
  )
  
```

```{r}
do_mean %>%
  filter(tide == "L") %>%
  filter(low_Immersed == "Y")%>%
  ggplot(aes(x = datetime, y = mean_DO, color = density))+
  scale_x_datetime(limits = as.POSIXct(c("2025-08-19 00:00:00","2025-08-28 00:00:00")))+
  geom_point()+
  theme_classic()+
  scale_color_manual(values = c( "black", "darkorange" ,"gold"), labels = c("Ambient", "Dense (300/bag)", "Sparse (150/bag)"))+
  labs(x = "Date", y = "DO (mg/L)", color = "Bag density")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))+
  ylim(0,22)
```

```{r}
do_mean %>%
  filter(tide == "H") %>%
  filter(up_Immersed == "Y")%>%
  ggplot(aes(x = datetime, y = mean_DO, color = density))+
  scale_x_datetime(limits = as.POSIXct(c("2025-08-19 00:00:00","2025-08-28 00:00:00")))+
  geom_point()+
  theme_classic()+
  scale_color_manual(values = c( "black", "darkorange" ,"gold"), labels = c("Ambient", "Dense (300/bag)", "Sparse (150/bag)"))+
  labs(x = "Date", y = "DO (mg/L)", color = "Bag density")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))+
  ylim(0,22)
```

```{r}
do_mean_wide <- do_mean %>%
  pivot_wider(names_from = density, values_from = mean_DO)

# Calculate differences
do_diff <- do_mean_wide %>%
  group_by(tide)%>%
  mutate(D_diff = D - C,
         S_diff = S - C,
         DS_diff = D- S) 

```

```{r}
do_diff %>%
  filter(tide == "H") %>%
  ggplot(aes(x = datetime))+
  geom_point(aes(y=D_diff), color = "yellow")+
  geom_point(aes(y =S_diff), color = "green")+
  theme_classic()+
  geom_hline(yintercept = 0)
```

```{r}

do_diff %>%
  filter(tide == "L") %>%
  filter(low_Immersed == "Y")%>%
  ggplot(aes(x = datetime))+
  geom_point(aes(y=D_diff), color = "yellow")+
  geom_point(aes(y =S_diff), color = "green")+
  theme_classic()+
  geom_hline(yintercept = 0)
```

```{r}

do_diff %>%
  filter(tide == "L") %>%
  filter(low_Immersed == "Y")%>%
  ggplot(aes(x = datetime))+
  geom_point(aes(y=DS_diff), color = "blue")+
  theme_classic()+
  geom_hline(yintercept = 0)
```

```{r}

do_diff %>%
  filter(tide == "H") %>%
  filter(up_Immersed == "Y")%>%
  ggplot(aes(x = datetime))+
  geom_point(aes(y=DS_diff), color = "blue")+
  theme_classic()+
  geom_hline(yintercept = 0)
```

### Means of DO diffs (density treatment vs control)

```{r}
do_diff_H <- do_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")

do_diff_L <- do_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")


mean(do_diff_H$D_diff)
sd(do_diff_H$D_diff)
mean(do_diff_H$S_diff)
sd(do_diff_H$S_diff)
mean(do_diff_H$DS_diff)
sd(do_diff_H$DS_diff)

mean(do_diff_L$D_diff)
sd(do_diff_L$D_diff)
mean(do_diff_L$S_diff)
sd(do_diff_L$S_diff)
mean(do_diff_L$DS_diff)
sd(do_diff_L$DS_diff)

```

### Is there a difference between dense and sparse racks

```{r}
do_rack_mean <- do_current %>%
  group_by(datetime, rack, density, tide) %>%
  summarize(mean_DO = mean(DO_adj),
            low_Immersed = first(low_Immersed),
            up_Immersed = first(up_Immersed),
            .groups = "drop")
```

```{r}
do_rack_mean %>%
  filter(tide == "L") %>%
  filter(low_Immersed == "Y")%>%
  filter(density == "C") %>%
  ggplot(aes(x = datetime, y = mean_DO, color = rack))+
  geom_point()+
  theme_classic()
```

```{r}
do_rack_mean %>%
  filter(tide == "H") %>%
  filter(up_Immersed == "Y")%>%
  filter(density == "C") %>%
  ggplot(aes(x = datetime, y = mean_DO, color = rack))+
  geom_point()+
  theme_classic()+
  ylim(2,20)
```

```{r}
do_rack_mean_wide <- do_rack_mean %>%
  pivot_wider(names_from = c(density, rack), values_from = mean_DO)

# Calculate differences
do_rack_diff <- do_rack_mean_wide %>%
  group_by(tide)%>%
  mutate(C_diff = C_S - C_D,
         D_diff = D_S - D_D,
         S_diff = S_S - S_D) 
  
```

```{r}
do_rack_diff %>%
  filter(tide == "H") %>%
  filter(up_Immersed == "Y") %>%
  ggplot(aes(x = datetime))+
  geom_point(aes(y=D_diff), color = "yellow")+
  geom_point(aes(y =S_diff), color = "green")+
  geom_point(aes(y=C_diff), color = "blue")+
  theme_classic()+
  geom_hline(yintercept = 0)
```

```{r}
do_rack_diff %>%
  filter(tide == "L") %>%
  filter(low_Immersed == "Y") %>%
  ggplot(aes(x = datetime))+
  geom_point(aes(y=D_diff), color = "yellow")+
  geom_point(aes(y =S_diff), color = "green")+
  geom_point(aes(y=C_diff), color = "blue")+
  theme_classic()+
  geom_hline(yintercept = 0)
```

```{r}
do_rack_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")%>%
  pull(D_diff) %>%
  mean(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")%>%
  pull(D_diff) %>%
  sd(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")%>%
  pull(S_diff) %>%
  mean(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")%>%
  pull(S_diff) %>%
  sd(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")%>%
  pull(C_diff) %>%
  mean(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "Y")%>%
  pull(C_diff) %>%
  sd(na.rm = TRUE)


# Low tide
do_rack_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")%>%
  pull(D_diff) %>%
  mean(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")%>%
  pull(D_diff) %>%
  sd(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")%>%
  pull(S_diff) %>%
  mean(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")%>%
  pull(S_diff) %>%
  sd(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")%>%
  pull(C_diff) %>%
  mean(na.rm = TRUE)

do_rack_diff %>%
  filter(tide == "L")%>%
  filter(low_Immersed == "Y")%>%
  pull(C_diff) %>%
  sd(na.rm = TRUE)


```

```{r}
do_mean$day <- as.Date(do_mean$datetime)

do_maxmin <- do_mean %>% 
  group_by(density, tide, day) %>%
  summarise(
    daymax_DO = max(mean_DO, na.rm = TRUE),
    daymax_DO_time = datetime[which.max(mean_DO)],
    daymin_DO = min(mean_DO, na.rm = TRUE),
    daymin_DO_time = datetime[which.min(mean_DO)],
    low_Immersed = first(low_Immersed),
    up_Immersed = first(up_Immersed),
    .groups = "drop"
  )

do_maxmin <- do_mean %>%
  filter(
    (tide == "H" & up_Immersed == "Y") |
    (tide == "L" & low_Immersed == "Y")
  ) %>%
  group_by(day, tide, density) %>%   # add other grouping vars if needed
  summarise(
    daymax_DO = max(mean_DO, na.rm = TRUE),
    daymax_DO_time = datetime[which.max(mean_DO)],
    daymin_DO = min(mean_DO, na.rm = TRUE),
    daymin_DO_time = datetime[which.min(mean_DO)],
    .groups = "drop"
  )
```

```{r}
lowtide_minplot <- do_maxmin %>%
  filter(tide == "L")%>%
  filter(density %in% c("C", "D", "S"))%>%
  ggplot(aes(x=daymin_DO_time, y=daymin_DO, color = density))+
  geom_line()+
  scale_color_manual(values = c("blue", "purple", "black"), labels = c("Ambient (no oysters)", "Dense (300/bag)", "Sparse (150/bag)"))+
  labs(x = "Date", y = "Daily minimum DO (mg/L)", color = "Bag density")+
  theme_classic()+
  theme(axis.text.y = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_text(color="black",size = 18),
    axis.title.x = element_text(color="black",size = 20),
    legend.text =  element_text(color="black",size = 18),
    legend.title = element_text(color="black",size = 20))+
  ylim(1,11); lowtide_minplot
```

```{r}
hitide_minplot <- do_maxmin %>%
  filter(tide == "H")%>%
  filter(density %in% c("C", "D", "S"))%>%
  ggplot(aes(x=daymin_DO_time, y=daymin_DO, color = density))+
  geom_line()+
  scale_color_manual(values = c("black", "darkorange", "gold"), labels = c("Ambient (no oysters)", "Dense (300/bag)", "Sparse (150/bag)"))+
  geom_hline(yintercept = 3, linetype = "dashed", color = "red")+
  labs(x = "Date", y = "Daily minimum DO (mg/L)", color = "Bag density")+
  theme_classic()+
  theme(axis.title.x = element_blank(),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_blank(),       # Change x-axis text size
    axis.text.y = element_text(color="black",size = 18),
    legend.position = "none")+
  ylim(1,11); hitide_minplot
```

```{r}
do_maxmin %>%
  filter(tide == "L")%>%
  filter(density %in% c("C", "D", "S"))%>%
  ggplot(aes(y = do_)) + 
  geom_histogram(alpha=0.2, position="identity")
```

```{r}
do_diff_long <- do_diff %>%
  subset(select = -c(C, D, S))%>%
  pivot_longer(cols = ends_with("diff"), names_to = "treatment", values_to = "DO_diff")

do_diff_long$day <- as.Date(do_diff_long$datetime)

do_diff_maxmin <- do_diff_long %>%
  group_by(tide, treatment, day)%>%
  summarise(daymin = min(DO_diff),
         daymax = max(DO_diff),
         .groups = 'drop') 
  
```

```{r}
do_diff_maxmin %>%
  filter(tide == "L")%>%
  ggplot(aes(x=day))+
  geom_line(aes(y=daymin, color = treatment))+
  theme_classic()+
  ylim(-4, 0)
```

```{r}
do_diff_long %>%
  filter(treatment == "D_diff") %>%
  group_by(tide) %>%
  summarise(
    median_DO_diff = median(DO_diff, na.rm = TRUE))

do_diff_long %>%
  filter(treatment == "DS_diff") %>%
  group_by(tide) %>%
  summarise(
    median_DO_diff = median(DO_diff, na.rm = TRUE))

do_diff_long %>%
  filter(treatment == "S_diff") %>%
  group_by(tide) %>%
  summarise(
    median_DO_diff = median(DO_diff, na.rm = TRUE))

do_diff_long %>%
  filter(treatment == "D_diff")%>%
  ggplot(aes(y=DO_diff, fill= tide))+
  geom_histogram(position = "identity",
    alpha = 0.8,
    bins = 30)+
  scale_fill_manual(values = c("#a6caec",  "#215f9a"), labels = c("MLW", "MLLW"))+
  labs(x = "Frequency", y = "Dense-Ambient DO (mg/L)", fill = "Tide height")+
  theme_classic()+
  geom_hline(yintercept = -0.28)+
  geom_hline(yintercept = -0.63)+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20),
    legend.text =element_text(color="black",size = 18),
    legend.title = element_text(color="black",size = 20))

do_diff_long %>%
  filter(treatment == "DS_diff")%>%
  ggplot(aes(y=DO_diff, fill= tide))+
  geom_histogram(position = "identity",
    alpha = 0.8,
    bins = 30)+
  scale_fill_manual(values = c("#a6caec",  "#215f9a"), labels = c("MLW", "MLLW"))+
  labs(x = "Frequency", y = "Dense-Sparse DO (mg/L)", fill = "Tide")+
  geom_hline(yintercept = -0.09)+
  geom_hline(yintercept = -0.14)+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20),
    legend.text =element_text(color="black",size = 18),
    legend.title = element_text(color="black",size = 20))

do_diff_long %>%
  filter(treatment == "S_diff")%>%
  ggplot(aes(y=DO_diff, fill= tide))+
  geom_histogram(position = "identity",
    alpha = 0.8,
    bins = 30)+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))



```

## Getting tide data going

```{r}
June_tide <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/Jun_tide.xlsx", col_names = TRUE)
June_tide <- June_tide[-1,]
Jul_tide <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/Jul_tide.xlsx", col_names = TRUE)
Jul_tide <- Jul_tide[-1,]
Aug_tide <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/DO/Aug_tide.xlsx", col_names = TRUE)
Aug_tide <- Aug_tide[-1,]

DO_tide <- bind_rows(June_tide, Jul_tide, Aug_tide)

colnames(DO_tide) <- c("info", "date", "day", "H_L", "pred_height", "pred_height2", "time", "data_range", "units", "datum", "disclaimer",	"EndDate",	"IntervalType",	"origin",	"producttype",	"state",	"stationid",	"stationidagg",	"stationname",	"stationtype",	"Timezone")

DO_tide$date <- as.Date(DO_tide$date)
DO_tide$time <- as_hms(strptime(DO_tide$time, format = "%I:%M %p"))
DO_tide$pred_height <- as.numeric(DO_tide$pred_height)

DO_tide$datetime <- as.POSIXct(paste(DO_tide$date, DO_tide$time), format="%Y-%m-%d %H:%M:%S")



```

```{r}
ggplot(DO_tide, aes(x=date, y=pred_height))+
  geom_point()+
  geom_line()+
  theme_classic()
```

```{r}
ggplot(DO_tide, aes(x=datetime, y=pred_height))+
  geom_point()+
  geom_line()+
  theme_classic()
```

```{r}
DO_tide_2 <- DO_tide %>%
  select(c("date", "datetime", "pred_height"))
```

```{r}

do_maxmin <- do_mean %>% 
  group_by(density, tide, day) %>%
  summarise(
    daymax_DO = max(mean_DO, na.rm = TRUE),
    daymax_DO_time = datetime[which.max(mean_DO)],
    daymin_DO = min(mean_DO, na.rm = TRUE),
    daymin_DO_time = datetime[which.min(mean_DO)],
    .groups = "drop"
  )

do_maxmin_long <- do_maxmin %>%
  pivot_longer(
    cols = c(daymax_DO, daymax_DO_time,
             daymin_DO, daymin_DO_time),
    names_to = c("stat", ".value"),
    names_pattern = "^day(max|min)_(DO(?:_time)?)$"
  )

do_maxmin_long <- do_maxmin_long %>%
  rename(datetime = DO_time)

do_maxmin_long <- do_maxmin_long %>%
  rename(date = day)


DO_withtides <- bind_rows(DO_tide_2, do_maxmin_long)


```

```{r}
DO_withtides %>% 
  filter(stat == "min")%>% 
  filter(tide == "L")%>% 
  ggplot(aes(x=datetime, y=pred_height))+
  geom_point()+
  geom_point(aes(y=DO, color = density))+
  geom_line()+
  theme_classic()
```

```{r}
DO_withtides <- DO_withtides %>%
  filter(date < "2025-08-29" & date > "2025-06-23")

tide_plot <- DO_tide %>%
  filter(date < "2025-08-20" & date > "2025-06-23")%>%
  ggplot(aes(x=datetime, y=pred_height))+
  geom_line(color = "blue")+
  geom_point(color = "blue")+
  labs(x = "Datetime",
       y= "Predicted tide height (ft)")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 18, color= "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 20, color= "black"),
        legend.text = element_text(size = 18, color= "black"),
        legend.title = element_text(size = 20, color= "black")); tide_plot



```

```{r}
gridExtra::grid.arrange(tide_plot, hitide_minplot, lowtide_minplot, ncol = 1)
```

## Do diff with immersion data

```{r}

do_diff_long <- do_diff %>%
  subset(select = -c(C, D, S))%>%
  pivot_longer(cols = ends_with("diff"), names_to = "treatment", values_to = "DO_diff")

do_diff_long$day <- as.Date(do_diff_long$datetime)

do_diff_maxmin <- do_diff_long %>%
  filter(
    (tide == "H" & up_Immersed == "Y") |
    (tide == "L" & low_Immersed == "Y")
  ) %>%
  group_by(day, tide, treatment) %>%   # add other grouping vars if needed
  summarise(
    daymax_DO = max(DO_diff, na.rm = TRUE),
    daymax_DO_time = datetime[which.max(DO_diff)],
    daymin_DO = min(DO_diff, na.rm = TRUE),
    daymin_DO_time = datetime[which.min(DO_diff)],
    .groups = "drop"
  )
```

```{r}
lowtide_mindiffplot <- do_diff_maxmin %>%
  filter(tide == "L")%>%
  filter(treatment %in% c("DS_diff", "D_diff", "S_diff"))%>%
  ggplot(aes(x=daymin_DO_time, y=daymin_DO, color = treatment))+
  geom_line()+
  geom_hline(yintercept = 0, linetype = "dashed")+
  scale_color_manual(values = c("darkorange",  "black", "gold"), labels = c("Dense (300/bag)", "Dense - Sparse", "Sparse (150/bag)"))+
  labs(x = "Date", y = "Daily minimum DO (mg/L)", color = "Bag density")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))+
  ylim(-4,0); lowtide_mindiffplot
```

```{r}
hitide_mindiffplot <- do_diff_maxmin %>%
  filter(tide == "H")%>%
  filter(treatment %in% c("DS_diff", "D_diff", "S_diff"))%>%
  ggplot(aes(x=daymin_DO_time, y=daymin_DO, color = treatment))+
  geom_line()+
  geom_hline(yintercept = 0, linetype = "dashed")+
  scale_color_manual(values = c("darkorange",  "black", "gold"), labels = c("Dense (300/bag)", "Dense - Sparse", "Sparse (150/bag)"))+
  labs(x = "Date", y = "Daily minimum DO (mg/L)", color = "Bag density")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))+
  ylim(-4,0); hitide_mindiffplot
```

```{r}
submersion_time_low <- do_mean %>%
  filter(tide == "L") %>%
  filter(low_Immersed == "Y")%>%
  group_by(day) %>%
  summarise(low_count_per_day = n()/3)

submersion_time_high <- do_mean %>%
  filter(tide == "H") %>%
  filter(up_Immersed == "Y")%>%
  group_by(day) %>%
  summarise(high_count_per_day = n()/3)

submersion_time_high$hours <- submersion_time_high$high_count_per_day * 5 /60
submersion_time_low$hours <- submersion_time_low$low_count_per_day * 5 /60

```

```{r}
submersion_time <- left_join(submersion_time_high, submersion_time_low, by = c("day"))

submersion_time_long <- submersion_time %>%
  rename(
    hours_high = hours.x,
    hours_low  = hours.y
  ) %>%
  pivot_longer(
    cols = c(high_count_per_day, low_count_per_day,
             hours_high, hours_low),
    names_to = c("HL", ".value"),
    names_pattern = "(high|low)_(.*)"
  ) %>%
  mutate(
    HL = ifelse(HL == "high", "H", "L")
  )


submersion_time_long <- na.omit(submersion_time_long)


```

```{r}
labels <- c("C" = "Ambient","D" = "Dense (2 layers, 300 oysters)","S" = "Sparse (1 layer, 150 oysters)")


mean_do_maxmin <- do_maxmin %>%
  group_by(density, tide) %>%
  filter(day < "2025-08-29", day > "2025-06-24")%>%
  summarise(mean_max = mean(daymax_DO, na.rm = TRUE),
            sde_max = sd(daymax_DO, na.rm = TRUE)/sqrt(length(daymax_DO)),
            mean_min = mean(daymin_DO, na.rm = TRUE),
            sde_min = sd(daymin_DO, na.rm = TRUE)/sqrt(length(daymin_DO)),
            .groups = 'drop')


mean_do_maxmin %>%
  mutate(density = factor(density, levels = c("D", "S", "C"))) %>%
  ggplot()+
  geom_point(aes(x = density,y=mean_min, color = density, shape = tide), size = 10)+
  scale_color_manual(values = c("purple","black","forestgreen" ), labels = c("Bottom (Dense)","Top (Dense)", "Solo (Sparse)"))+
  labs(x = "Density treatment", y = "Daily minimum DO (mg/L)", color = "Density treatment", shape = "Tide Height")+
  scale_x_discrete(labels = c("D" = "Dense (Top and Bottom)","S" = "Sparse","C" = "Ambient (no oysters)")) +
  geom_errorbar(aes(x= density, ymin=mean_min-sde_min, ymax=mean_min+sde_min, color = density, group = tide), width=.2)+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20),
    legend.text =element_text(color="black",size = 18),
    legend.title = element_text(color="black",size = 20))
```
