---
title: "robo"
output: html_document
date: "2025-07-14"
---
### Load libraries
```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(readxl)
library(lubridate)
library(purrr)
install.packages("gridExtra")
library(gridExtra)
```

### Load data
```{r}


files <- list.files(path = "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/04192026")

robo<- data.frame()

for (file in files){
  name <- gsub(".csv","", file)
  robo_file <- read_csv(paste("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/04192026/",file, sep = ""))
  robo_file <- robo_file[-c(1:21), ]
  robo_file$sensor <- name
  robo <- rbind(robo, robo_file)
}

colnames(robo) <- c("datetime", "temp", "robo_sensor")
robo$datetime <- as.POSIXct(robo$datetime, format = "%Y-%m-%d %H:%M")


```


```{r}
robo_sensor_key <- read_excel("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/robo_sensor_key_post08072025.xlsx")
robo_sensor_key$robo_sensor <- as.character(robo_sensor_key$robo_sensor)
robo$robo_sensor <- as.character(robo$robo_sensor)
robo$temp <- as.numeric(robo$temp)

robo <- left_join(robo, robo_sensor_key, by = "robo_sensor")
robo$bag <- as.factor(robo$bag)

robo$datetime <- as.POSIXct(robo$datetime, format = "%Y-%m-%d %H:%M", tz = "America/Los_Angeles")

robo$datetime <- robo$datetime - hours(8)

write.csv(robo, "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/04192026/robo_comb.csv")

```


```{r}

ggplot(robo, aes(x=datetime, y=temp, colour = robo_sensor))+
  geom_line()+
  theme_classic()

```

```{r}
robo %>%
  filter(bag == c(43:46, 27:30))%>%
  filter(top_bottom == c("1", "2", "0"))%>%
  ggplot(aes(x=datetime, y=temp, colour = top_bottom))+
  geom_line()+
  theme_classic()
```

```{r}
robo %>%
  filter(bag == c(43:46, 27:30))%>%
  filter(density == "S")%>%
  #filter(top_bottom == c("1", "2"))%>%
  ggplot(aes(x=datetime, y=temp, colour = bag))+
  geom_line()+
  theme_classic()
```

```{r}
robo %>%
  filter(bag == c(93:100))%>%
  filter(top_bottom == c("1", "2", "0"))%>%
  ggplot(aes(x=datetime, y=temp, colour = top_bottom))+
  geom_line()+
  theme(axis.text = element_text(size = 18, color = "black"),
        axis.title = element_text(size = 20, color = "black"))+
  labs(color = "Bag Position",
       x = "Date", 
       y = "Temperature (°C)")+
  theme_classic()
```
```{r}
robo %>%
  filter(bag == c(93:100))%>%
  filter(density == "S")%>%
  #filter(top_bottom == c("1", "2"))%>%
  ggplot(aes(x=datetime, y=temp, colour = bag))+
  geom_line()+
  theme_classic()
```

```{r}
robo %>%
  filter(bag == c(93:100))%>%
  filter(density == "C")%>%
  ggplot(aes(x=datetime, y=temp, colour = bag))+
  geom_line()+
  theme_classic()
```

```{r}

robo %>%
  filter(bag == c(27:46))%>%
  filter(density == "C")%>%
  ggplot(aes(x=datetime, y=temp, colour = bag))+
  geom_line()+
  theme_classic()
```
### Interpolate temps where sensors were offset 
```{r}
library(dplyr)
library(zoo)

# Define your reference and comparison sensors
ref_sensor_id <- "oyster_2"
other_sensors <- c("oyster_6", "oyster_7", "oyster_8")

# Step 1: Get the reference sensor data
sensor_ref <- robo %>%
  filter(robo_sensor == ref_sensor_id) %>%
  arrange(datetime) %>%
  select(datetime, temp) 

# Step 2: Interpolate each comparison sensor to reference timestamps
interpolated_matrix <- sapply(other_sensors, function(sensor_id) {
  sensor_target <- robo %>%
    filter(robo_sensor == sensor_id) %>%
    arrange(datetime)
  
  z <- zoo(sensor_target$temp, sensor_target$datetime)
  na.approx(z, xout = sensor_ref$datetime)
})


long_interp <- imap_dfr(interpolated_matrix, function(zoo_obj, sensor_name) {
  tibble(
    datetime = index(zoo_obj),
    interpolated_temp = coredata(zoo_obj),
    oyster_id = sensor_name
  )
})

colnames(long_interp) <- c("datetime", "temp", "robo_sensor")

long_interp <- left_join(long_interp, robo_sensor_key, by = "robo_sensor")
long_interp$bag <- as.factor(long_interp$bag)

```


### Add interpolated temps in, take uninterped ones out
```{r}
robo_filtered <- robo %>%
  filter(!robo_sensor %in% c("oyster_6", "oyster_7", "oyster_8"))

robo_interp <- bind_rows(robo_filtered, long_interp)
write.csv(robo_interp, "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/09152025/interp_comb.csv")

write.csv(robo, "/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/10102025/robo_comb.csv")

```

### combine interp files
```{r}
interp1 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/07102025/interp_comb.csv")
interp2 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/08062025/interp_comb.csv")
interp3 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/09152025/interp_comb.csv")
robo1 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/10102025/robo_comb.csv")
robo2 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/11062025/robo_comb.csv")
robo3 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/12022025/robo_comb.csv")
robo4 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/01162026/robo_comb.csv")
robo5 <- read.csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Robo/04192026/robo_comb.csv")


interp <- bind_rows(interp1, interp2, interp3, robo1, robo2, robo3, robo4, robo5)

interp$datetime <- as.POSIXct(interp$datetime, format = "%Y-%m-%d %H:%M:%S",  tz = "America/Los_Angeles")

```



```{r}
robo_interp_mean <- interp %>%
  group_by(datetime, density, tide, top_bottom) %>%
  summarize(mean_temp = mean(temp))
```



```{r}
robo_interp_mean$top_bottom <- as.factor(robo_interp_mean$top_bottom)
robo_interp_mean <- robo_interp_mean %>% mutate(top_bottom = factor(top_bottom, levels = c("2", "0", "1", "SC", "DC")))

robo_interp_mean_filtered <- robo_interp_mean %>%
  filter(minute(datetime) %in% c(0, 15, 30, 45))

robo_interp_mean %>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("2"))%>%
  ggplot(aes(x=datetime, y=mean_temp))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  geom_line(color = "#a6caec")+
  labs(x = "Date", y = "Oyster temperature")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))+
  ylim(0,40)

robo_interp_mean_filtered %>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("2"))%>%
  ggplot(aes(x=datetime, y=mean_temp))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  geom_line(color = "#a6caec")+
  labs(x = "Date", y = "Oyster temperature")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))+
  ylim(0,40)


robo_interp_mean %>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("0"))%>%
  ggplot(aes(x=datetime, y=mean_temp))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  geom_line()+
  theme_classic()
```


```{r}
robo_interp_mean %>%
  filter(top_bottom %in% c("2"))%>%
  #filter(month(datetime) == 9)%>%
  ggplot(aes(x=datetime, y=mean_temp, colour = tide))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  scale_x_datetime(limits = as.POSIXct(c("2025-07-25 00:00:00","2025-07-26 00:00:00")))+
  labs(x = "Date", y = "Oyster temperature")+
  scale_color_manual(values = c("#a6caec",  "#215f9a"), labels = c("MLW", "MLLW"))+
  geom_line()+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))
```

## Temp Diff calc
```{r}
robo_mean_wide <- robo_interp_mean_filtered %>%
  pivot_wider(names_from = c(density, top_bottom), values_from = mean_temp)

robo_mean_wide_tide <- robo_interp_mean_filtered %>%
  pivot_wider(names_from = c(top_bottom, tide), values_from = mean_temp)


# Calculate differences
temp_diff <- robo_mean_wide %>%
  group_by(tide)%>%
  mutate(D_diff = ((D_2*9/5)+32)- ((D_1*9/5)+32),
         top_diff = ((D_2*9/5)+32) - ((S_0*9/5)+32),
         bot_diff = ((S_0*9/5)+32)-((D_1*9/5)+32),
         C_diff = ((C_SC*9/5)+32) - ((C_DC*9/5)+32)) 

temp_diff_tide <- robo_mean_wide_tide %>%
  mutate(two_diff = (`2_H`*9/5)+32-(`2_L`*9/5)+32,
         one_diff = `1_H`*9/5-`1_L`,
         zero_diff = `0_H`-`0_L`) 


```

```{r}
temp_diff %>%
  filter(tide == "L")%>%
  ggplot(aes(x=datetime, y=C_diff))+
  geom_line(color = "darkred")+
  theme_classic()+
  geom_hline(yintercept = 0)+
  labs(x = "Date", y = "Oyster temperature")+
  theme_classic()+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20))
  
```


```{r}
library(lubridate)

## only for summer data

temp_diff_immersion <- left_join(temp_diff, current, by = "datetime")
temp_diff_immersion$up_Immersed <- ifelse(temp_diff_immersion$up_speed < 10,  "Y", "N" )
temp_diff_immersion$low_Immersed <- ifelse(temp_diff_immersion$low_speed < 10,  "Y", "N" )

temp_diff_immersion %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "N")%>%
  summarise(
    median_top_diff = median(top_diff, na.rm = TRUE))

temp_diff_immersion %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "N")%>%
  summarise(
    median_D_diff = median(D_diff, na.rm = TRUE))

temp_diff_immersion %>%
  filter(tide == "H")%>%
  filter(up_Immersed == "N")%>%
  summarise(
    median_bot_diff = median(bot_diff, na.rm = TRUE))




temp_diff_immersion %>%
  filter(tide == "H")%>%
    filter(datetime > "2025-08-29 00:00:00" & datetime< "2025-10-15 00:00:00")%>%
  #filter(month(datetime) == 10)%>%
  ggplot()+
  geom_boxplot(aes(y=D_diff, fill = "darkred"))+
  #geom_histogram(aes(y=D_diff), fill = "green",position = "identity",
    # alpha = 0.8,
    # bins = 30)+
  labs(x = "Frequency", y = "Top (Dense) - Bottom (Dense) (°F)")+
  #geom_line(aes(y = C_diff), color = "steelblue")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20),
    axis.text.x = element_blank(),
    axis.title.x = element_blank())
```

```{r}
temp_diff %>%
  filter(tide == "H")%>%
  ggplot(aes(x=datetime))+
  geom_line(aes(y=D_diff), color = "tomato")+
  #geom_line(aes(y = C_diff), color = "steelblue")+
  theme_classic()
```

```{r}
temp_diff %>%
  filter(tide == "L")%>%
  ggplot(aes(x=datetime))+
  geom_line(aes(y=top_diff), color = "gold")+
  #geom_line(aes(y = C_diff), color = "steelblue")+
  theme_classic()
```

```{r}
temp_diff %>%
  filter(tide == "H")%>%
  ggplot(aes(x=datetime))+
  geom_line(aes(y=top_diff), color = "gold")+
  #geom_line(aes(y = C_diff), color = "steelblue")+
  theme_classic()


median(temp_diff$top_diff, na.rm = TRUE)
median(temp_diff$D_diff, na.rm = TRUE)
```


```{r}
robo_interp_mean_filtered$day <- as.Date(robo_interp_mean_filtered$datetime- hours(7))

robo_maxmin <- robo_interp_mean_filtered %>%
  group_by(density, tide, top_bottom, day)%>%
  summarise(daymin = min(mean_temp),
         daymax = max(mean_temp),
         .groups = 'drop') 
  
  
```



```{r}
robo_maxmin %>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("1", "2", "0"))%>%
  ggplot(aes(x=day))+
  geom_line(aes(y=daymax, color = top_bottom))+
  scale_color_manual(values = c("darkorange","black",  "gold"), labels = c("Dense (top layer)", "Sparse (solo bag)", "Dense (bottom layer)"))+
  theme_classic()
```

```{r}
robo_maxmin %>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("1", "2", "0"))%>%
  ggplot(aes(x=day))+
  geom_line(aes(y=daymin, color = top_bottom))+
  theme_classic()
```


```{r}
robo_maxmin %>%
  filter(tide == "L")%>%
  filter(top_bottom %in% c("1", "2", "0"))%>%
  ggplot(aes(x=day))+
  geom_line(aes(y=daymax, color = top_bottom))+
  theme_classic()
```


```{r}
robo_maxmin %>%
  filter(tide == "L")%>%
  filter(top_bottom %in% c("1", "2", "0"))%>%
  ggplot(aes(x=day))+
  geom_line(aes(y=daymin, color = top_bottom))+
  theme_classic()
```


```{r}

robo_maxmin %>%
  filter(tide == "H")%>%
  filter(top_bottom== "2")%>%
  filter(day < "2025-08-29")%>%
  summarise(
    median_top_max = median(daymax, na.rm = TRUE))

robo_maxmin %>%
  filter(tide == "H")%>%
  filter(top_bottom== "0")%>%
  filter(day < "2025-08-29")%>%
  summarise(
    median_top_max = median(daymax, na.rm = TRUE))

robo_maxmin %>%
  filter(tide == "L")%>%
  filter(top_bottom== "2")%>%
  filter(day < "2025-08-29")%>%
  summarise(
    median_top_max = median(daymax, na.rm = TRUE))

robo_maxmin %>%
  filter(tide == "L")%>%
  filter(top_bottom== "0")%>%
  filter(day < "2025-08-29")%>%
  summarise(
    median_top_max = median(daymax, na.rm = TRUE))

robo_maxmin %>%
  filter(tide == "L")%>%
  filter(top_bottom== "2")%>%
  filter(day > "2025-08-29")%>%
  summarise(
    median_top_max = median(daymax, na.rm = TRUE))

robo_maxmin %>%
  filter(tide == "L")%>%
  filter(top_bottom== "0")%>%
  filter(day >"2025-08-29")%>%
  summarise(
    median_top_max = median(daymax, na.rm = TRUE))


robo_mean_immersion <- left_join(robo_interp_mean, current, by = "datetime")
robo_mean_immersion$up_Immersed <- ifelse(robo_mean_immersion$up_speed < 10,  "Y", "N" )
robo_mean_immersion$low_Immersed <- ifelse(robo_mean_immersion$low_speed < 10,  "Y", "N" )


temp_maxmin_immersion <- robo_mean_immersion%>%
  filter(
    (tide == "H" & up_Immersed == "N") |
    (tide == "L" & low_Immersed == "N")
  ) %>%
  group_by(day, tide, density, top_bottom) %>%   # add other grouping vars if needed
  summarise(
    daymax_temp = max(mean_temp, na.rm = TRUE),
    daymax_temp_time = datetime[which.max(mean_temp)],
    daymin_temp = min(mean_temp, na.rm = TRUE),
    daymin_temp_time = datetime[which.min(mean_temp)],
    .groups = "drop"
  )


robo_maxmin %>%
  filter(day < "2025-08-29")%>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("0", "1", "2"))%>%
  ggplot(aes(x=day))+
  geom_point(aes(y=daymax, color = top_bottom))+
  theme_classic()

```
```{r}
robo_maxmin %>%
  mutate(top_bottom = factor(top_bottom, levels = c("0", "2", "1"))) %>%
  filter(day < "2025-08-29")%>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("0", "1"))%>%
  ggplot()+
  geom_histogram(aes(y=daymax, fill = top_bottom),position = "identity",
    alpha = 0.8,
    bins = 30)+
  scale_fill_manual(values = c("gold", "orange"), labels = c("Solo (Sparse)", "Bottom (Dense)"))+
  theme_classic()
```


```{r}
robo_maxmin  %>%
  mutate(top_bottom = factor(top_bottom, levels = c("1", "2", "0"))) %>%
  filter(day < "2025-08-29", day > "2025-06-24",
         tide == "L",
         top_bottom %in% c("0", "2", "1"))%>%
  ggplot()+
  geom_boxplot(aes(x = top_bottom, y=(daymax*9/5)+32, fill = top_bottom))+
  scale_fill_manual(values = c("dodgerblue","tomato","black" ), labels = c("Bottom (Dense)","Top (Dense)", "Solo (Sparse)"))+
  scale_x_discrete(labels = c("0" = "Solo (Sparse)","2" = "Top (Dense)","1" = "Bottom (Dense)")) +
  labs(x = "Bag position/Treatment", y = "Daily maximum oyster temperature (°C)", fill = "Bag position")+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20),
    legend.text =element_text(color="black",size = 18),
    legend.title = element_text(color="black",size = 20))+
  ylim(60, 105)
```

### Prez graph

```{r}
mean_robo_maxmin <- robo_maxmin %>%
  group_by(density, tide, top_bottom) %>%
  filter(day < "2025-08-29", day > "2025-06-24")%>%
  summarise(mean_max = mean(daymax, na.rm = TRUE),
            sde_max = sd(daymax, na.rm = TRUE)/sqrt(length(daymax)),
            mean_min = mean(daymin, na.rm = TRUE),
            sde_min = sd(daymin, na.rm = TRUE)/sqrt(length(daymin)),
            .groups = 'drop')


mean_robo_maxmin %>%
  mutate(top_bottom = factor(top_bottom, levels = c("1", "2", "0"))) %>%
  filter(top_bottom %in% c("1", "2", "0"))%>%
  ggplot()+
  geom_point(aes(x = top_bottom,y=(mean_max*9/5)+32, color = top_bottom, shape = tide), size = 10)+
  geom_line(aes(x = top_bottom,y=(mean_max*9/5)+32, linetype = tide), linewidth = 5)+
  scale_color_manual(values = c("dodgerblue","tomato","black" ), labels = c("Dense (Bottom)","Dense (Top)", "Sparse"))+
  labs(x = "Bag position/Treatment", y = "Daily maximum oyster temperature (°F)", color = "Bag position", shape = "Tide Height")+
  scale_x_discrete(labels = c("0" = "Sparse","2" = "Dense (Top)","1" = "Dense (Bottom)")) +
  geom_errorbar(aes(x= top_bottom, ymin=((mean_max-sde_max)*9/5)+32, ymax=((mean_max+sde_max)*9/5)+32, color = top_bottom, group = tide), width=.2)+
  theme_classic()+
  theme(axis.text = element_text(color="black",size = 18),      # Change x-axis title size
    axis.title = element_text(color="black",size = 20),
    legend.text =element_text(color="black",size = 18),
    legend.title = element_text(color="black",size = 20))
```

