---
title: "survival"
output: html_document
date: "2025-07-10"
---

### Load libraries
```{r}
library(ggplot2)
library(tidyverse)
library(readxl)
install.packages("lme4")
library(lme4)
install.packages("glmmTMB")
library(glmmTMB)
install.packages("DHARMa")
library(DHARMa)
```


### Load data
```{r}
setwd("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field")

survival <- read_xlsx("data/Survival/04192026.xlsx")
treat_key <- read_xlsx("data/treatment_key.xlsx")

colnames(survival) <- c("date", "bag_num", "dead", "init_live_ImageJ")
survival$bag_num <- as.factor(survival$bag_num)
treat_key$bag_num <- as.factor(treat_key$bag_num)
survival <- left_join(survival, treat_key, by = "bag_num")
survival$top_bottom <- as.factor(survival$top_bottom)

```

### Cumulative deaths
```{r}

survival <- survival %>%
  group_by(bag_num, top_bottom) %>%
  arrange(date)%>%
  mutate(cumulative_deaths = cumsum(dead)) %>%
  ungroup()
```


```{r}
means_cumdead <- survival %>%
  group_by(date, density, tide, top_bottom) %>%
  summarise(mean_cumdead = mean(cumulative_deaths, , na.rm = TRUE),
            std_error = sd(cumulative_deaths, na.rm = TRUE)/sqrt(length(cumulative_deaths)),
            .groups = 'drop')
```


```{r}
means_cumdead %>%
  filter(tide == "H")%>%
  ggplot(aes(x = date, y = mean_cumdead, color = top_bottom)) +
   geom_point(size=3, position=position_dodge(0.05)) +
  geom_line(linewidth = 2, linetype = "dashed")+
  labs(x = "Date",
       y = "Cumulative dead oysters per bag") +
  #scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  labs(color = "Bag position/treatment")+
  scale_color_manual(
    values = c(
      "0" = "gold",
      "1" = "darkorange",
      "2" = "darkred"
    ), labels = c("Solo (Sparse)", "Bottom (Dense)", "Top (Dense)"))+
  geom_errorbar(aes(ymin=mean_cumdead-std_error, ymax=mean_cumdead+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,40)+
  theme(axis.title.x = element_text(color="black",size = 20),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_text(color="black",size = 18),       # Change x-axis text size
    axis.text.y = element_text(color="black",size = 18),
    legend.text = element_text(color="black",size = 18),      # Change legend text size
    legend.title = element_text(color="black",size = 20))
```

```{r}
means_cumdead %>%
  filter(tide == "L")%>%
  filter(top_bottom %in% c("2", "1"))%>%
  ggplot(aes(x = date, y = mean_cumdead, color = top_bottom)) +
   geom_point(size=3, position=position_dodge(0.05)) +
  geom_line(linewidth = 2, linetype = "dashed")+
  labs(x = "Date",
       y = "Cumulative dead oysters per bag") +
  #scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  labs(color = "Bag position/treatment")+
  scale_color_manual(
    values = c(
      "1" = "darkorange",
      "2" = "darkred"
    ), labels = c("Solo (Sparse)", "Bottom (Dense)", "Top (Dense)"))+
  geom_errorbar(aes(ymin=mean_cumdead-std_error, ymax=mean_cumdead+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,40)+
  theme(axis.title.x = element_text(color="black",size = 20),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_text(color="black",size = 18),       # Change x-axis text size
    axis.text.y = element_text(color="black",size = 18),
    legend.text = element_text(color="black",size = 18),      # Change legend text size
    legend.title = element_text(color="black",size = 20))
```




```{r}
means_cumdead %>%
  filter(tide == "H")%>%
  #filter(date < "2025-10-15")%>%
  filter(top_bottom == "2")%>%
  ggplot(aes(x = date, y = mean_cumdead, color = top_bottom)) +
   geom_point(size=3, position=position_dodge(0.05)) +
  geom_line(linewidth = 2)+
  labs(x = "Date",
       y = "Cumulative dead oysters per bag") +
  #scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  labs(color = "Bag position")+
  scale_color_manual(
    values = c(
      "0" = "gold",
      "1" = "darkorange",
      "2" = "darkred"
    ), labels = c("Solo (Sparse)", "Bottom (Dense)", "Top (Dense"))+
  geom_errorbar(aes(ymin=mean_cumdead-std_error, ymax=mean_cumdead+std_error), width=.2,
                 position=position_dodge(0.05))+
  
  theme_classic()+
  ylim(0,35)+
  theme(axis.title.x = element_text(color="black",size = 20),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_text(color="black",size = 18),       # Change x-axis text size
    axis.text.y = element_text(color="black",size = 18),
    legend.text = element_text(color="black",size = 18),      # Change legend text size
    legend.title = element_text(color="black",size = 20))
```


```{r}
means_cumdead %>%
  filter(tide == "H")%>%
  filter(top_bottom %in% c("2", "1"))%>%
  filter(date < "2025-10-15")%>%
  ggplot(aes(x = date, y = mean_cumdead, color = top_bottom)) +
   geom_point(size=3, position=position_dodge(0.05)) +
  geom_line(linewidth = 2, linetype = "solid")+
  labs(x = "Date",
       y = "Cumulative dead oysters per bag") +
  #scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  scale_x_datetime(date_labels = "%b %Y", date_breaks = "1 month") +
  labs(color = "Bag position/treatment")+
  scale_color_manual(values = c("1" = "darkorange","2" = "darkred"), labels = c("Bottom (Dense)", "Top (Dense)"))+
  geom_errorbar(aes(ymin=mean_cumdead-std_error, ymax=mean_cumdead+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,35)+
  theme(axis.title.x = element_text(color="black",size = 20),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_text(color="black",size = 18),       # Change x-axis text size
    axis.text.y = element_text(color="black",size = 18),
    legend.text = element_text(color="black",size = 18),      # Change legend text size
    legend.title = element_text(color="black",size = 20))
```


```{r}
survival <- survival %>%
  group_by(bag_num, top_bottom) %>%
  arrange(date)%>%
  mutate(alive_num = init_live_ImageJ-cumulative_deaths) %>%
  ungroup()

survival$date <- as.POSIXct(survival$date)
survival$days <- as.numeric(survival$date - min(survival$date))
survival$days <- survival$days/86400
survival$days <- survival$days + 16

survival_summer <- survival %>%
  filter(date < "2025-09-30")
```

## Models with summer data
### Model 1
```{r}
model1 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~  top_bottom+ tide + piling + rack + (1|days)+(1|bag_num),  data = survival_summer, family = binomial()) #glmmTMB
summary(model1)
testDispersion(model1)
tst_simres <- simulateResiduals(fittedModel = model1) #DHARMa
plot(tst_simres)


car::Anova(model1 , type = "III")

```
### Model 2
```{r}
model2 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~ top_bottom*tide + piling + rack +(1|days)+(1|bag_num),  data = survival_summer, family = binomial()) #glmmTMB
summary(model2)
```
### Model 3
```{r}
model3 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~  tide * top_bottom + piling+(1|days)+(1|bag_num),  data = survival_summer, family = binomial()) #glmmTMB
summary(model3)
```

### Model 4
```{r}
model4 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~ tide * top_bottom +(1|days) +(1|bag_num),  data = survival_summer, family = binomial()) #glmmTMB
summary(model4)

testDispersion(model4)
tst_simres <- simulateResiduals(fittedModel = model4) #DHARMa
plot(tst_simres)


car::Anova(model4 , type = "III")

### Maybe run a kaplan meier curve?? Does that make sense for this??? Look into it
```


### Emmeans
```{r}
library(emmeans)

emm_by_tide <- emmeans(model4, ~ top_bottom | tide)
contrast(emm_by_tide, method = "pairwise")


emm_inter <- emmeans(model4, ~ tide * top_bottom)
contrast(emm_inter, method = "pairwise", by = "tide")

contrast(emm_inter, method = "pairwise", by = "top_bottom")


contrast(emm_inter, interaction = "pairwise")

emm_tb <- emmeans(
  model4,
  ~ top_bottom | tide 
)

emm_tb2 <- emmeans(
  model4,
  ~ tide | top_bottom 
)

pairs(emm_tb,adjust = "sidak")
pairs(emm_tb2,adjust = "sidak")

```

## Models with full data
I think I need to restructure this based on seasonality, isolating cumulative survival by season
### Model 1
```{r}
model1 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~  top_bottom+ tide + piling + rack + (1|days)+(1|bag_num),  data = survival, family = binomial()) #glmmTMB
summary(model1)
testDispersion(model1)
tst_simres <- simulateResiduals(fittedModel = model1) #DHARMa
plot(tst_simres)

install.packages("car")
library(car)
car::Anova(model1 , type = "III")

```
### Model 2
```{r}
model2 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~ top_bottom*tide + piling + rack +(1|days)+(1|bag_num),  data = survival, family = binomial()) #glmmTMB
summary(model2)
```
### Model 3
```{r}
model3 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~  tide * top_bottom + piling+(1|days)+(1|bag_num),  data = survival, family = binomial()) #glmmTMB
summary(model3)
```

### Model 4
```{r}
model4 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~ tide * top_bottom +(1|days) +(1|bag_num),  data = survival, family = binomial()) #glmmTMB
summary(model4)

testDispersion(model4)
tst_simres <- simulateResiduals(fittedModel = model4) #DHARMa
plot(tst_simres)


car::Anova(model4 , type = "III")

### Maybe run a kaplan meier curve?? Does that make sense for this??? Look into it
```


### Emmeans
```{r}
install.packages("emmeans")
library(emmeans)

emm_by_tide <- emmeans(model4, ~ top_bottom | tide)
contrast(emm_by_tide, method = "pairwise")


emm_inter <- emmeans(model4, ~ tide * top_bottom)
contrast(emm_inter, method = "pairwise", by = "tide")

contrast(emm_inter, method = "pairwise", by = "top_bottom")


contrast(emm_inter, interaction = "pairwise")

emm_tb <- emmeans(
  model4,
  ~ top_bottom | tide 
)

emm_tb2 <- emmeans(
  model4,
  ~ tide | top_bottom 
)

pairs(emm_tb,adjust = "sidak")
pairs(emm_tb2,adjust = "sidak")

```



### Model 8
```{r}
model8 <-glmmTMB(cbind(alive_num, cumulative_deaths) ~  top_bottom+(1|days)+(1|bag_num),  data = survival, family = binomial()) #glmmTMB
summary(model8)

```



### Raw survival
```{r}
means_dead <- survival %>%
  group_by(date, density, tide, top_bottom) %>%
  summarise(mean_dead = mean(dead, , na.rm = TRUE),
            std_error = sd(dead, na.rm = TRUE)/sqrt(length(dead)),
            .groups = 'drop')

survival$month <- month(survival$date)


means_dead %>%
  filter(tide == "H")%>%
  ggplot(aes(x = date, y = mean_dead, color = top_bottom)) +
   geom_point(size=3, position=position_dodge(0.05)) +
  #geom_line(aes(linetype = tide))+
  labs(x = "Date",
       y = "Mean dead oysters per bag") +
  #scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  labs(color = "Bag position")+
  geom_errorbar(aes(ymin=mean_dead-std_error, ymax=mean_dead+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,13)
```

```{r}
means_dead %>%
  filter(tide == "L")%>%
  ggplot(aes(x = date, y = mean_dead, color = top_bottom)) +
   geom_point(size=3, position=position_dodge(0.05)) +
  #geom_line(aes(linetype = tide))+
  labs(x = "Date",
       y = "Mean dead oysters per bag") +
  #scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  labs(color = "Bag position")+
  geom_errorbar(aes(ymin=mean_dead-std_error, ymax=mean_dead+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,13)
```
## Mean dead models
```{r}
model1 <-glmmTMB(dead ~  top_bottom* tide + piling + rack +month +(1|bag_num),  data = survival, family = nbinom2()) #glmmTMB
summary(model1)
testDispersion(model1)
tst_simres <- simulateResiduals(fittedModel = model1) #DHARMa
plot(tst_simres)


car::Anova(model1 , type = "III")
```


```{r}
model2 <-glmmTMB(dead ~  top_bottom*tide*month + piling +rack +(1|bag_num),  data = survival, family = nbinom2()) #glmmTMB
summary(model2)
testDispersion(model2)
tst_simres <- simulateResiduals(fittedModel = model2) #DHARMa
plot(tst_simres)


car::Anova(model2 , type = "III")
```


```{r}
model3 <-glmmTMB(dead ~  top_bottom*tide*month + piling +(1|bag_num),  data = survival, family = nbinom2()) #glmmTMB
summary(model3)
testDispersion(model3)
tst_simres <- simulateResiduals(fittedModel = model3) #DHARMa
plot(tst_simres)


car::Anova(model3 , type = "III")
```



```{r}
model4 <-glmmTMB(dead ~  top_bottom*tide+month+(1|bag_num),  data = survival, family = nbinom2()) #glmmTMB
summary(model4)
testDispersion(model4)
tst_simres <- simulateResiduals(fittedModel = model4) #DHARMa
plot(tst_simres)


car::Anova(model4 , type = "III")
```


```{r}
survival$month <- month(survival$date)
survival$month <- as.factor(survival$month)

model5 <-glmmTMB(dead ~  top_bottom*tide*month+(1|bag_num),  data = survival, family = nbinom2()) #glmmTMB
summary(model5)
testDispersion(model5)
tst_simres <- simulateResiduals(fittedModel = model5) #DHARMa
plot(tst_simres)


car::Anova(model5 , type = "III")

hist(survival$dead)

```

```{r}
library(emmeans)

emm_by_tide <- emmeans(model4, ~ top_bottom | tide)
contrast(emm_by_tide, method = "pairwise")


emm_inter <- emmeans(model4, ~ month | top_bottom * tide)
pairs(emm_inter,adjust = "sidak")

contrast(emm_inter, method = "pairwise", by = "top_bottom")


contrast(emm_inter, interaction = "pairwise")


emm_tb <- emmeans(
  model5,
  ~ top_bottom | tide * month
)

pairs(emm_tb,adjust = "sidak")
```


### Prez graph

```{r}




means_cumdead %>%
  mutate(top_bottom = factor(top_bottom, levels = c("1", "2", "0"))) %>%
  filter(date == as.Date("2025-09-15"))%>%
  ggplot(aes(x = top_bottom, y = mean_cumdead, color = top_bottom, shape = tide)) +
   geom_point(size=10, position=position_dodge(0.05)) +
  geom_line(linewidth = 2, linetype = "solid")+
  labs(x = "Bag position / Treatment",
       y = "Cumulative dead oysters per bag",
       shape = "Tide Height") +
  labs(color = "Bag position/treatment")+
  scale_color_manual(values = c("1" = "dodgerblue","2" = "tomato", "0" = "black"), labels = c("Dense (Bottom)", "Dense (Top)", "Sparse"))+
  scale_shape_manual(values = c("H" = "circle","L" = "triangle"), labels = c("High", "Low"))+
  geom_errorbar(aes(ymin=mean_cumdead-std_error, ymax=mean_cumdead+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  scale_x_discrete(
    labels = c("0" = "Sparse","1" = "Dense (Bottom)", "2" = "Dense (Top)")
  ) +
  ylim(0,35)+
  theme(axis.title.x = element_text(color="black",size = 20),      # Change x-axis title size
    axis.title.y = element_text(color="black",size = 20),      # Change y-axis title size
    axis.text.x = element_text(color="black",size = 18),       # Change x-axis text size
    axis.text.y = element_text(color="black",size = 18),
    legend.text = element_text(color="black",size = 18),      # Change legend text size
    legend.title = element_text(color="black",size = 20))




```

