---
title: "06242025_07092025_tilt"
output: html_document
date: "2025-07-09"
---

### Load libraries
```{r}
library(dplyr)
library(readr)
library(ggplot2)
```

### Load in data
```{r}

setwd("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/Density_field/data/Tilt/")

upper_1 <- read_csv("07092025/2403278_Westcott_upper_(0)_Current.csv")
colnames(upper_1) <- c("datetime", "up_speed", "up_head_deg", "up_vel_N", "up_vel_E")

up_temp1 <- read_csv("07092025/2403278_Westcott_upper_(0)_Temperature.csv")
colnames(up_temp1) <- c("datetime", "up_temp")

upper_2 <- read_csv("07232025/2403278_Westcott_upper_(1)_Current.csv")
colnames(upper_2) <- c("datetime", "up_speed", "up_head_deg", "up_vel_N", "up_vel_E")

up_temp2 <- read_csv("07232025/2403278_Westcott_upper_(1)_Temperature.csv")
colnames(up_temp2) <- c("datetime", "up_temp")

upper_3 <- read_csv("08062025/2403278_Westcottupper23_(0)_Current.csv")
colnames(upper_3) <- c("datetime", "up_speed", "up_head_deg", "up_vel_N", "up_vel_E")

up_temp3 <- read_csv("08062025/2403278_Westcottupper23_(0)_Temperature.csv")
colnames(up_temp3) <- c("datetime", "up_temp")

upper_4 <- read_csv("08192025/2403278_westcottupper86_(1)_Current.csv")
colnames(upper_4) <- c("datetime", "up_speed", "up_head_deg", "up_vel_N", "up_vel_E")

up_temp4 <- read_csv("08192025/2403278_westcottupper86_(1)_Temperature.csv")
colnames(up_temp4) <- c("datetime", "up_temp")

upper_5 <- read_csv("09152025/2403278_westcottup0819_(0)_Current.csv")
colnames(upper_5) <- c("datetime", "up_speed", "up_head_deg", "up_vel_N", "up_vel_E")

up_temp5 <- read_csv("09152025/2403278_westcottup0819_(0)_Temperature.csv")
colnames(up_temp5) <- c("datetime", "up_temp")


lower_1 <- read_csv("07092025/2308203_Westcott_lower_(0)_Current.csv")
colnames(lower_1) <- c("datetime", "low_speed", "low_head_deg", "low_vel_N", "low_vel_E")

low_temp1 <- read_csv("07092025/2308203_Westcott_lower_(0)_Temperature.csv")
colnames(low_temp1) <- c("datetime", "low_temp")

lower_2 <- read_csv("07232025/2308203_Westcott_lower_(1)_Current.csv")
colnames(lower_2) <- c("datetime", "low_speed", "low_head_deg", "low_vel_N", "low_vel_E")

low_temp2 <- read_csv("07232025/2308203_Westcott_lower_(1)_Temperature.csv")
colnames(low_temp2) <- c("datetime", "low_temp")

lower_3 <- read_csv("08062025/2308203_Westcottlower23_(0)_Current.csv")
colnames(lower_3) <- c("datetime", "low_speed", "low_head_deg", "low_vel_N", "low_vel_E")

low_temp3 <- read_csv("08062025/2308203_Westcottlower23_(0)_Temperature.csv")
colnames(low_temp3) <- c("datetime", "low_temp")

lower_4 <- read_csv("08192025/2308203_westcottlower86_(0)_Current.csv")
colnames(lower_4) <- c("datetime", "low_speed", "low_head_deg", "low_vel_N", "low_vel_E")

low_temp4 <- read_csv("08192025/2308203_westcottlower86_(0)_Temperature.csv")
colnames(low_temp4) <- c("datetime", "low_temp")

lower_5 <- read_csv("09152025/2308203_westcottlow0813_(1)_Current.csv")
colnames(lower_5) <- c("datetime", "low_speed", "low_head_deg", "low_vel_N", "low_vel_E")

low_temp5 <- read_csv("09152025/2308203_westcottlow0813_(1)_Temperature.csv")
colnames(low_temp5) <- c("datetime", "low_temp")

current1 <- upper_1 %>%
  left_join(lower_1, by = "datetime")%>%
  left_join(up_temp1, by = "datetime")%>%
  left_join(low_temp1, by = "datetime")

current2 <- upper_2 %>%
  left_join(lower_2, by = "datetime")%>%
  left_join(up_temp2, by = "datetime")%>%
  left_join(low_temp2, by = "datetime")

current3 <- upper_3 %>%
  left_join(lower_3, by = "datetime")%>%
  left_join(up_temp3, by = "datetime")%>%
  left_join(low_temp3, by = "datetime")

current4 <- upper_4 %>%
  left_join(lower_4, by = "datetime")%>%
  left_join(up_temp4, by = "datetime")%>%
  left_join(low_temp4, by = "datetime")

current5 <- upper_5 %>%
  left_join(lower_5, by = "datetime")%>%
  left_join(up_temp5, by = "datetime")%>%
  left_join(low_temp5, by = "datetime")

current <- bind_rows(current1, current2, current3, current4, current5)

```

### Tidal current speeds
```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_speed), color = "tomato")+
  geom_point(aes(y = low_speed), color="steelblue")+
   scale_x_datetime(limits = as.POSIXct(c("2025-08-12 00:00:00","2025-08-14 00:00:00")))+
  theme_classic()



```


### Temperature data
```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_temp), color = "tomato")+
  geom_point(aes(y = low_temp), color="steelblue")+
  theme_classic()

```

```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_speed), color = "tomato")+
  geom_point(aes(y = low_speed), color="steelblue")+
  theme_classic()+
  scale_x_datetime(limits = as.POSIXct(c("2025-07-01 00:00:00", "2025-07-10 12:00:00")))+
  ylim(0,10)
```

```{r}
ggplot(current, aes(x=datetime,))+
  geom_point(aes(y = up_temp), color = "tomato")+
  geom_point(aes(y = low_temp), color="steelblue")+
  theme_classic()+
  scale_x_datetime(limits = as.POSIXct(c("2025-07-03 00:00:00", "2025-07-04 12:00:00")))
```

```{r}
current_lim <-current %>%
  filter(low_speed <= 10)%>%
  filter(up_speed <= 10)

mean(current_lim$up_speed)

mean(current_lim$low_speed)



```

